CREATE TABLE IF NOT EXISTS `video_pipeline_tasks` (
  `id` bigint(20) NOT NULL AUTO_INCREMENT,
  `task_key` varchar(64) NOT NULL,
  `manuscript_id` int(11) NOT NULL,
  `video_id` int(11) NOT NULL,
  `uploader_id` int(11) DEFAULT NULL,
  `video_title` varchar(255) DEFAULT NULL,
  `current_step_index` int(11) NOT NULL DEFAULT 0,
  `status` varchar(32) NOT NULL,
  `worker_id` varchar(128) DEFAULT NULL,
  `locked_until` datetime DEFAULT NULL,
  `failed_step` varchar(64) DEFAULT NULL,
  `error_message` varchar(500) DEFAULT NULL,
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `start_time` datetime DEFAULT NULL,
  `end_time` datetime DEFAULT NULL,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  KEY `idx_vpt_task_key_id` (`task_key`, `id`),
  KEY `idx_vpt_status_create` (`status`, `create_time`),
  KEY `idx_vpt_status_lock` (`status`, `locked_until`),
  KEY `idx_vpt_video_status` (`video_id`, `status`),
  KEY `idx_vpt_manuscript_status` (`manuscript_id`, `status`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
