server:
  port: 8082

spring:
  application:
    name: mybilibili-video
  main:
    allow-circular-references: true
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybilibili?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf8&autoReconnect=true&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 127.0.0.1
    port: 6379
    database: 1
  data:
    mongodb:
      uri: mongodb://localhost:27017/mybilibili
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        import-check:
          enabled: false
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

upload:
  base-path: d:/files/mybilibili/uploads

project:
  folder: d:/files/mybilibili/uploads

rocketmq:
  name-server: 127.0.0.1:9876

logging:
  level:
    com.mybilibili: debug