server:
  port: 8084

spring:
  application:
    name: mybilibili-search
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        enabled: false
        server-addr: 127.0.0.1:8848
        file-extension: yaml
  elasticsearch:
    uris: http://127.0.0.1:9200
  data:
    redis:
      host: 127.0.0.1
      port: 6379
    mongodb:
      uri: mongodb://127.0.0.1:27017/mybilibili
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybilibili?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: ${MYSQL_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: never

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: auto

logging:
  level:
    com.mybilibili: debug
